-- Execute este arquivo uma vez no SQL Editor depois do schema.sql.
-- Ele pode ser executado novamente sem apagar produtos.

alter table public.products drop constraint if exists products_category_check;
alter table public.products add column if not exists stock_quantity integer not null default 0 check (stock_quantity >= 0);
alter table public.products add column if not exists archived boolean not null default false;

create table if not exists public.categories (
  id uuid primary key default gen_random_uuid(),
  name text not null unique check (char_length(name) between 2 and 50),
  sort_order integer not null default 0,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

insert into public.categories (name, sort_order) values
  ('Perfume',1),('Colônia',2),('Sabonete',3),('Desodorante',4),
  ('Kit',5),('Roupas',6),('Acessórios',7)
on conflict (name) do nothing;

create table if not exists public.admin_devices (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  installation_id text not null,
  device_info jsonb not null default '{}'::jsonb,
  ip_address text,
  last_location jsonb,
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  unique (user_id, installation_id)
);

create table if not exists public.audit_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  installation_id text not null,
  action text not null,
  details jsonb not null default '{}'::jsonb,
  ip_address text,
  location jsonb,
  created_at timestamptz not null default now()
);

alter table public.categories enable row level security;
alter table public.admin_devices enable row level security;
alter table public.audit_events enable row level security;

drop policy if exists "catálogo público" on public.products;
create policy "catálogo público" on public.products
for select to anon, authenticated using ((active and not archived) or public.is_admin());

drop policy if exists "categorias públicas" on public.categories;
create policy "categorias públicas" on public.categories
for select to anon, authenticated using (active or public.is_admin());

drop policy if exists "admin cadastra categorias" on public.categories;
create policy "admin cadastra categorias" on public.categories
for insert to authenticated with check (public.is_admin());

drop policy if exists "admin altera categorias" on public.categories;
create policy "admin altera categorias" on public.categories
for update to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists "admin exclui categorias" on public.categories;
create policy "admin exclui categorias" on public.categories
for delete to authenticated using (public.is_admin());

drop policy if exists "admin registra aparelho" on public.admin_devices;
create policy "admin registra aparelho" on public.admin_devices
for insert to authenticated with check (user_id = auth.uid() and public.is_admin());

drop policy if exists "admin atualiza aparelho" on public.admin_devices;
create policy "admin atualiza aparelho" on public.admin_devices
for update to authenticated using (user_id = auth.uid() and public.is_admin())
with check (user_id = auth.uid() and public.is_admin());

drop policy if exists "admin consulta aparelhos" on public.admin_devices;
create policy "admin consulta aparelhos" on public.admin_devices
for select to authenticated using (public.is_admin());

drop policy if exists "admin registra evento" on public.audit_events;
create policy "admin registra evento" on public.audit_events
for insert to authenticated with check (user_id = auth.uid() and public.is_admin());

drop policy if exists "admin consulta eventos" on public.audit_events;
create policy "admin consulta eventos" on public.audit_events
for select to authenticated using (public.is_admin());

grant select on public.categories to anon, authenticated;
grant insert, update, delete on public.categories to authenticated;
grant select, insert, update on public.admin_devices to authenticated;
grant select, insert on public.audit_events to authenticated;
grant usage, select on sequence public.audit_events_id_seq to authenticated;
