-- CONFIGURAÇÃO PRINCIPAL DA LOJA DA DEDEIA
-- Pode ser executada novamente sem apagar produtos.
-- Este arquivo não depende do Supabase Storage.

create extension if not exists pgcrypto;

create table if not exists public.admins (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create table if not exists public.products (
  id uuid primary key default gen_random_uuid(),
  name text not null check (char_length(name) between 2 and 120),
  category text not null,
  price numeric(10,2) not null check (price >= 0),
  old_price numeric(10,2) check (old_price is null or old_price >= 0),
  image_url text not null,
  active boolean not null default true,
  stock_quantity integer not null default 0 check (stock_quantity >= 0),
  archived boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Atualiza instalações antigas sem apagar os produtos existentes.
alter table public.products drop constraint if exists products_category_check;
alter table public.products add column if not exists stock_quantity integer not null default 0 check (stock_quantity >= 0);
alter table public.products add column if not exists archived boolean not null default false;

create table if not exists public.categories (
  id uuid primary key default gen_random_uuid(),
  name text not null unique check (char_length(name) between 2 and 50),
  sort_order integer not null default 0,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

insert into public.categories (name, sort_order) values
  ('Perfume', 1),
  ('Colônia', 2),
  ('Sabonete', 3),
  ('Desodorante', 4),
  ('Kit', 5),
  ('Roupas', 6),
  ('Acessórios', 7)
on conflict (name) do nothing;

create table if not exists public.admin_devices (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  installation_id text not null,
  device_info jsonb not null default '{}'::jsonb,
  ip_address text,
  last_location jsonb,
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  unique (user_id, installation_id)
);

create table if not exists public.audit_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  installation_id text not null,
  action text not null,
  details jsonb not null default '{}'::jsonb,
  ip_address text,
  location jsonb,
  created_at timestamptz not null default now()
);

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1 from public.admins where user_id = auth.uid()
  )
$$;

alter table public.admins enable row level security;
alter table public.products enable row level security;
alter table public.categories enable row level security;
alter table public.admin_devices enable row level security;
alter table public.audit_events enable row level security;

drop policy if exists "admin lê seu acesso" on public.admins;
create policy "admin lê seu acesso" on public.admins
for select to authenticated using (user_id = auth.uid());

drop policy if exists "catálogo público" on public.products;
create policy "catálogo público" on public.products
for select to anon, authenticated
using ((active and not archived) or public.is_admin());

drop policy if exists "admin cadastra produtos" on public.products;
create policy "admin cadastra produtos" on public.products
for insert to authenticated with check (public.is_admin());

drop policy if exists "admin altera produtos" on public.products;
create policy "admin altera produtos" on public.products
for update to authenticated
using (public.is_admin()) with check (public.is_admin());

drop policy if exists "admin exclui produtos" on public.products;
create policy "admin exclui produtos" on public.products
for delete to authenticated using (public.is_admin());

drop policy if exists "categorias públicas" on public.categories;
create policy "categorias públicas" on public.categories
for select to anon, authenticated using (active or public.is_admin());

drop policy if exists "admin cadastra categorias" on public.categories;
create policy "admin cadastra categorias" on public.categories
for insert to authenticated with check (public.is_admin());

drop policy if exists "admin altera categorias" on public.categories;
create policy "admin altera categorias" on public.categories
for update to authenticated
using (public.is_admin()) with check (public.is_admin());

drop policy if exists "admin exclui categorias" on public.categories;
create policy "admin exclui categorias" on public.categories
for delete to authenticated using (public.is_admin());

drop policy if exists "admin registra aparelho" on public.admin_devices;
create policy "admin registra aparelho" on public.admin_devices
for insert to authenticated
with check (user_id = auth.uid() and public.is_admin());

drop policy if exists "admin atualiza aparelho" on public.admin_devices;
create policy "admin atualiza aparelho" on public.admin_devices
for update to authenticated
using (user_id = auth.uid() and public.is_admin())
with check (user_id = auth.uid() and public.is_admin());

drop policy if exists "admin consulta aparelhos" on public.admin_devices;
create policy "admin consulta aparelhos" on public.admin_devices
for select to authenticated using (public.is_admin());

drop policy if exists "admin registra evento" on public.audit_events;
create policy "admin registra evento" on public.audit_events
for insert to authenticated
with check (user_id = auth.uid() and public.is_admin());

drop policy if exists "admin consulta eventos" on public.audit_events;
create policy "admin consulta eventos" on public.audit_events
for select to authenticated using (public.is_admin());

grant usage on schema public to anon, authenticated;
grant select on public.products to anon, authenticated;
grant insert, update, delete on public.products to authenticated;
grant select on public.categories to anon, authenticated;
grant insert, update, delete on public.categories to authenticated;
grant select on public.admins to authenticated;
grant select, insert, update on public.admin_devices to authenticated;
grant select, insert on public.audit_events to authenticated;
grant usage, select on sequence public.audit_events_id_seq to authenticated;

-- Resultado visível para confirmar a instalação.
select table_name as tabela_criada
from information_schema.tables
where table_schema = 'public'
  and table_name in ('admins','products','categories','admin_devices','audit_events')
order by table_name;
